### ISSUE TITLE
apply (all) color maps in Odemis Viewer (Windows)

### ISSUE THREAD

**Issue by EvdWee** [delmic/odemis#2305]
It would be really useful to be able to apply all color maps to correlative images in Odemis Viewer on Windows.
Right now the selection is quite limited, as compared to Odemis (Viewer) in Linux.

**Comment by pieleric** [comment]
Dear Ernest,
Due to the Christmas holiday, the release of the new Odemis Viewer for Windows got delayed. You should now be able to update Odemis to v3.2.1, which includes the new "colourmap" feature. You can do it either from Odemis (in the menu Help/Check for updates), or by going to our website: https://www.delmic.com/en/learn/resource-library
