### ISSUE TITLE
Windows/Mac support?

### ISSUE THREAD

**Issue by thomasaarholt** [delmic/odemis#318]
I've been asked to help out with writing python scripts at the University of Oslo for use with Odemis. I primarily use Mac and Windows, and it would be nice to see support on those platforms. Has any work been done on supporting either of these?

**Comment by pieleric** [comment]
Odemis works in some limited way under Windows: you can run the GUI in viewer mode, and use the util/dataio modules to analyse data in Python. See the OdemisViewer installer (available at delmic.com), and the developer guide. On the other hand, the backend is very far from working on Windows.

MacOS is not supported, mostly just due to the lack of demand. I guess the hardest might be to develop the installer. Of course, patches are welcome.

In general, for such broad questions about Odemis, you can contact me directly by email: piel@delmic.com
