### ISSUE TITLE
Acquisition of spectrum image fails with Pyro4 error

### ISSUE THREAD

**Issue by thomasaarholt** [delmic/odemis#440]
I'm back after a 6-month hiatus doing other things. Since last time, odemis has been updated on our system here in Oslo (with the addition of a probe current acquisition setting, amongst other things), but now the script I've been running fails.

Running Odemis 2.6-449-gf76d97e, and `odemis.__version__` returns `2.6.6`.

Do you have any suggestions based on the error output?

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-36-22229b5cb031> in <module>()
----> 1 a = acquirer.start()
      2 #plt.imshow(a)

<ipython-input-34-25d7aa1609a4> in start(self)
    189         '''
    190         #SE = self.acquire_large_SE_image()
--> 191         SI = self.acquire_cube()
    192 
    193         return SI

<ipython-input-34-25d7aa1609a4> in acquire_cube(self)
    125 
    126         # synchronize the two devices
--> 127         self.spect.data.synchronizedOn(self.ebeam.newPosition)
    128 
    129         startt = time.time()

/usr/lib/python2.7/dist-packages/Pyro4/core.pyc in __call__(self, *args, **kwargs)
    163 
    164     def __call__(self, *args, **kwargs):
--> 165         return self.__send(self.__name, args, kwargs)
    166 
    167 

/usr/lib/python2.7/dist-packages/Pyro4/core.pyc in _pyroInvoke(self, methodname, vargs, kwargs, flags)
    308         data, compressed=self._pyroSerializer.serialize(
    309             (self._pyroConnection.objectId, methodname, vargs, kwargs),
--> 310             compress=Pyro4.config.COMPRESSION)
    311         if compressed:
    312             flags |= MessageFactory.FLAGS_COMPRESSED

/usr/lib/python2.7/dist-packages/Pyro4/util.pyc in serialize(self, data, compress)
    132         """Serialize the given data object, try to compress if told so.
    133         Returns a tuple of the serialized data (bytes) and a bool indicating if it is compressed or not."""
--> 134         data=self.pickle.dumps(data, self.pickle.HIGHEST_PROTOCOL)
    135         if not compress or len(data)<200:
    136             return data, False  # don't waste time compressing small messages

/usr/lib/python2.7/dist-packages/Pyro4/core.pyc in __call__(self, *args, **kwargs)
    163 
    164     def __call__(self, *args, **kwargs):
--> 165         return self.__send(self.__name, args, kwargs)
    166 
    167 

/usr/lib/python2.7/dist-packages/Pyro4/core.pyc in _pyroInvoke(self, methodname, vargs, kwargs, flags)
    331                         if sys.platform=="cli":
    332                             util.fixIronPythonExceptionForPickle(data, False)
--> 333                         raise data
    334                     else:
    335                         return data

AttributeError: 'CompositedScanner' object has no attribute 'newPosition.__getnewargs__'
```

**Comment by pieleric** [comment]
Hi Thomas,

(For such very site-specific issue, it's generally preferable to contact bugreport@delmic.com, than create an issue here. Anyway, in practice both work.)

Indeed, several things have changed on the system. In addition to the support for the PCD, it's now using a newer (development) version of Odemis, and can control the ebeam settings. That last change is causing issues with your script, because the "CompositedScanner" is merging the attributes of the control component and the e-beam scanner component, but doesn't duplicate the newPosition Event. You can work around it by doing in your script something like:
```
escan = model.getComponent(name="SEM E-beam")
:
self.spect.data.synchronizedOn(self.escan.newPosition)
```

That said, in my experience relying on the .newPosition to synchronise the spectrometer is not very reliable. If for some reasons the spectrometer is late (eg, because of some errors in the USB connection which delays the image arrival), it's pretty impossible to ever be sure you're observing precisely at the e-beam position. You can see how we do it in `src/odemis/acq/stream/_sync.py`.

**Comment by thomasaarholt** [comment]
Thanks Eric, I'll resort to bugreport now. I'd just spotted that you'd merged a pull request minutes before I wrote the error, so I wrote it here :smile: 

I'll send an email to bugreport now with a followup question.
